### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by SavMartin** [overmindstudios/BlenderUpdaterCLI#14]
![imagen](https://user-images.githubusercontent.com/30030642/70393569-44c12280-19e3-11ea-9f01-954c42014490.png)

**Comment by tobkum** [comment]
seems weird, works here. Can you try to omit the `-o linux` part and see if that changes anything? Let me know!
![image](https://user-images.githubusercontent.com/16955378/70431263-f3657180-1a7c-11ea-8077-3ec648ae1829.png)

**Comment by tobkum** [comment]
Can you omit `-o linux` and let me know if it works then?

**Comment by tobkum** [comment]
ahh, just saw they changed the linux file extension to .tar.xz from .tar.gz2. Can you download the latest version of BlenderUpdaterCLI and see if that works?

**Comment by SavMartin** [comment]
Yes , now its work perfect. thx

**Comment by tobkum** [comment]
Thanks for reporting!
