### ISSUE TITLE
Tool has problem to find the version

### ISSUE THREAD

**Issue by noemis84** [overmindstudios/BlenderUpdaterCLI#16]
hey there,
since last week, the tool seems to have problems to update blender.

`BlenderUpdaterCLI.exe -b 2.90 -p blender290`
This line worked for many weeks, but since some days I got the error:

`No valid Blender version specified (2.90 not found)`

Mayber there's a way, that the tool can show possible versions like:
'BlenderUpdaterCLI.exe -checkBuilds' gives you a list: 2.83,2.90,2.91... just an idea.

**Comment by tobkum** [comment]
Hey Simeon!

They changed the naming scheme, so now you have to change your script to
BlenderUpdaterCLI.exe -b 2.90.0 -p blender290

**Comment by tobkum** [comment]
Hey Simeon!

They changed the naming scheme, so now you have to change your script to
`BlenderUpdaterCLI.exe -b 2.90.0 -p blender290`

Listing the versions is a good idea, thanks!
