### ISSUE TITLE
Not works on Windows

### ISSUE THREAD

**Issue by millionart** [overmindstudios/BlenderUpdaterCLI#3]
Traceback (most recent call last):
  File "D:\Git\BlenderUpdaterCLI\BlenderUpdaterCLI.py", line 19, in <module>
    from colorama import init, Fore
ModuleNotFoundError: No module named 'colorama'

**Comment by tobkum** [comment]
You have to install the required modules before running the script

**Comment by millionart** [comment]
thanks, worked
