### ISSUE TITLE
Can't open blender.app on macOS

### ISSUE THREAD

**Issue by millionart** [overmindstudios/BlenderUpdaterCLI#4]
Download directly from the official website works well.

**Comment by millionart** [comment]
need run `sudo chmod -R 777 blender.app`
But I think this should be included in the updater, as well as the installation part of the python module.

**Comment by tobkum** [comment]
I'll check as soon as I get my hands on a Mac. If anyone is using OSX, PRs are welcome!

**Comment by millionart** [comment]
The logic in the code is to give permission before autorun, but I added the -n parameter, so this part is skipped.

**Comment by tobkum** [comment]
Ahh, gotcha! Thanks for clarification

**Comment by millionart** [comment]
Why you close this? You didn't fix it.

**Comment by tobkum** [comment]
I did fix it in the code locally here, will commit
