### ISSUE TITLE
Is the release up to date? Or not working...

### ISSUE THREAD

**Issue by noemis84** [overmindstudios/BlenderUpdaterCLI#9]
if I download the latest exe from releases it's not working for me:
the minimal example would be 
`BlenderUpdaterCLI.exe -p C:\Users\simeo\Desktop\blender2.81_nightly\`
but I get the error:
`error: the following arguments are required: -b/--blender`
but adding -b 28 brings:
`File "BlenderUpdaterCLI.py", line 199, in <module>
IndexError: list index out of range
[9984] Failed to execute script BlenderUpdaterCLI`

I could also try the python way, but everytime I did, I'd the wrong python, "PATH", Lib or whatever. using the exe was nice and straight.

**Comment by tobkum** [comment]
Oh, sorry - didn't update the release .exe. Can you try again with the lastest version (1.2) and let me know? No need for the -b flag anymore as well

**Comment by noemis84** [comment]
Thank you for updating the release! It's working again :)
